
[env]
TERM = "xterm-256color"
opacity = "0.6"

[font]
size = 13.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 4
y = 4

[general]
import = ["/Users/fumiyanakamura/.config/alacritty/catppuccin_theme/catppuccin-latte.toml"]

[window]
opacity = 0.6
blur = true

[keyboard]
bindings = [
  { key = "Enter", mods = "Alt", action = "ToggleFullscreen" }, # フルスクリーン切替
]

